# Generated by Django 4.2.4 on 2023-08-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('quantity', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
