# Generated by Django 4.2.4 on 2023-08-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
    ]
