# Generated by Django 4.2.4 on 2023-08-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='quantity',
        ),
    ]
