# Generated by Django 4.2.4 on 2023-08-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_client_item_alter_client_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
        migrations.AddField(
            model_name='client',
            name='item',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
