# Generated by Django 4.2.4 on 2023-08-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_client_username_client_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
