# Generated by Django 4.2.4 on 2023-08-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_client_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='username',
            new_name='name',
        ),
    ]
