# Generated by Django 4.2.4 on 2023-08-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_file_rename_username_client_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='client',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
