# Generated by Django 4.2.4 on 2023-08-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_name_client_customer_client_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
