# Generated by Django 4.2.4 on 2023-08-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_client_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='data',
            new_name='date',
        ),
    ]
