# Generated by Django 4.2.4 on 2023-08-27 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_data_client_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date',
        ),
    ]
