# Generated by Django 4.2.4 on 2023-08-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_client_spent_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gems',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
