# Generated by Django 4.2.4 on 2023-08-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_client_gems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gems',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
